DROP TABLE  LEGAL_PERSONS CASCADE CONSTRAINTS;
DROP TABLE  NATURAL_PERSONS CASCADE CONSTRAINTS;
DROP TABLE  AGENTS CASCADE CONSTRAINTS;
DROP TABLE  INSURANCES CASCADE CONSTRAINTS;
DROP TABLE  COMPANIES CASCADE CONSTRAINTS;
DROP TABLE  INSURANCE_TYPES CASCADE CONSTRAINTS;
DROP TABLE  COMPANIES_BY_INSURANCE_TYPE CASCADE CONSTRAINTS;
DROP TABLE  INSURANCE_ATTRIBUTES CASCADE CONSTRAINTS;
DROP TABLE  ATTRIBUTE_TYPES CASCADE CONSTRAINTS;
DROP TABLE INSURANCE_RATES;
DROP TABLE RATE_TYPES;
drop table USERS_AND_USERDATA;
/

DROP SEQUENCE insurance_rates_s;
DROP SEQUENCE insurance_attributes_s;
DROP SEQUENCE rate_type_s;
DROP SEQUENCE natural_persons_s;
DROP SEQUENCE legal_persons_s;
--DROP SEQUENCE clients_s;
DROP SEQUENCE agents_s;
DROP SEQUENCE insurances_s;
DROP SEQUENCE companies_s;
DROP SEQUENCE insurance_types_s;
DROP SEQUENCE companies_by_insurance_types_s;
DROP SEQUENCE attribute_types_s;
--DROP SEQUENCE static_attribute_s;
